name: Publish package to Github Packages

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 20.x
          scope: '@somosprte'
          registry-url: https://registry.npmjs.org

      - name: Install yarn globally
        run: npm install -g yarn

      - name: Install dependencies in production mode
        run: yarn install --production

      - name: Configure git user email
        run: git config --global user.email "${{ github.event.release.author.email }}"

      - name: Configure git user name
        run: git config --global user.name "${{ github.event.release.author.login }}"

      - name: Change package version
        run: yarn version --new-version ${{ github.event.release.tag_name }}

      - name: Publish package to Github Packages
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
