name: Publish package to Github Packages

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.5
          registry-url: https://npm.pkg.github.com/

      - name: Install yarn globally
        run: npm install -g yarn

      - name: Install dependencies in production mode
        run: yarn install --production

      - name: Create SSH directory
        run: mkdir -p ~/.ssh/

      - name: Add Github to known hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Put Private Key on SSH directory
        run: echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa

      - name: Change permissions to private key
        run: chmod 600 ~/.ssh/id_rsa

      - name: Configure git user email
        run: git config --global user.email "${{ github.event.release.author.email }}"

      - name: Configure git user name
        run: git config --global user.name "${{ github.event.release.author.login }}"

      - name: Fetch git branches
        run: git fetch --all

      - name: Change package version
        run: yarn version --new-version ${{ github.event.release.tag_name }}

      - name: Unstage package.json
        run: git reset HEAD~1

      - name: Stage package.json
        run: git add package.json

      - name: Commit package.json
        run: 'git commit -m "chore: release ${{ github.event.release.tag_name }}"'

      - name: Push changes to Github
        run: git push origin master

      - name: Publish package to Github Packages
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
